### ISSUE TITLE
Leaking CORS-headers

### ISSUE THREAD

**Issue by ssaarela** [NitorCreations/nflow#199]
Currently embedded nFlow puts default CORS headers (e.g. "access-control-allow-origin": "*")  to all requests in given Spring (Boot) application. These settings cannot be overridden by application. Could you make this feature configurable? Preferably nFlow's header-settings should not effect other endpoints of the application at all.

**Comment by efonsell** [comment]
Fixed in https://github.com/NitorCreations/nflow/pull/200

**Comment by efonsell** [comment]
Fixed in 3.3.0
