### ISSUE TITLE
The data is left in the inconsistent state if the nFlow database fails

### ISSUE THREAD

**Issue by yaskovdev** [NitorCreations/nflow#227]
I have two data sources: a database and a message queue.
I have two steps in my workflow: _Step A_ makes changes in the database, then _Step B_ sends a message to the message queue.

I use the next scenario:
1. I run the workflow
2. _Step A_ of the workflow makes changes in the database
3. I turn off the database (to simulate the fail)
4. nFlow tries to write to the database the fact that Step A is finished and obviously fails (log attached: [nflow-sandbox.log.txt](https://github.com/NitorCreations/nflow/files/1224779/nflow-sandbox.log.txt))
5. I turn on the database. As a result, _the data is in inconsistent state_: the changes were made in the database by _Step A_, but the notification was not sent by _Step B_.

Expected:
nFlow takes actions to make the data consistent again (e.g., starts the failed workflow from the beginning relying on the idempotency of the data sources).
Actual:
The data is left in the inconsistent state.

The project I use to reproduce the issue is here: https://github.com/yaskovdev/sandbox/tree/master/distributed-transaction-sandbox

**Comment by jsyrjala** [comment]
Thanks for the issue, we are looking into this.

**Comment by eputtone** [comment]
@yaskovdev, good finding!

Currently nFlow recovers workflow instances that were under execution when JVM was shutdown, but this mechanism does not cover temporary database failures when persisting the new state. Your case becomes a subject of recovery only after JVM restart (=the executing workflow instance is locked to a dead nFlow executor).

There's at least 2 ways to fix this:
1. As you mentioned, make nFlow retry the state execution when the database is available again (=recover workflow instances whose new state could not be saved)
2. Retry new state saving in nFlow until the database is available again. This does block the thread that is processing the workflow instance, but this should not be a problem as the database is down anyways.

Which way would be preferable in your case?

**Comment by yaskovdev** [comment]
I would prefer _the 2nd way_. Because there's no reason to start the whole workflow from the beginning: we can try to continue from the first failed action (from the saving of the new workflow state in our example).
I was trying to come up with a scenario where only the 1st of the proposed ways could make the data consistent again, but cannot invent it.
