### ISSUE TITLE
MSSQL support

### ISSUE THREAD

**Issue by tomaszglinski** [NitorCreations/nflow#239]
Hi, are you planning to add MSSQL support, and is there a chance that it will work now using one of other profiles?

**Comment by efonsell** [comment]
Hi, there is a branch for this:
https://github.com/NitorCreations/nflow/tree/mssql
If you can help finish it and make a pull request that would help.

**Comment by efonsell** [comment]
Fixed in 5.0.0 (https://github.com/NitorCreations/nflow/releases/tag/5.0.0)
