### ISSUE TITLE
Replace deprecated NCSARequestLog in StartNflow.java

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/nflow#289]
org.eclipse.jetty.server.NCSARequestLog gets deprecated in Jetty 9.4.15.v20190215 and our build will fail if using deprecated classes.

This class is used by [StartNflow.java](https://github.com/NitorCreations/nflow/blob/master/nflow-jetty/src/main/java/io/nflow/jetty/StartNflow.java#L238). Need to replace it with CustomRequestLog and RequestLogWriter when upgrading jetty.

**Comment by dahedgehog** [comment]
Fixed in pull request: https://github.com/NitorCreations/nflow/pull/298
