### ISSUE TITLE
WorkflowInstanceDao creates ArrayLists that are backed by massive empty arrays

### ISSUE THREAD

**Issue by ptorkko** [NitorCreations/nflow#306]
List<Integer> children = instance.childWorkflows.computeIfAbsent(parentActionId, ArrayList::new);

This actually ends up calling `new ArrayList(parentActionId)`, which causes ArrayLists with massive empty backing arrays relative in size to the age of the database.

**Comment by efonsell** [comment]
Will be fixed in 5.5.1 release. 5.5.1-SNAPSHOT is now available in Maven Central.

**Comment by jsyrjala** [comment]
@ptorkko 5.6.0 was just released with a fix for this issue. May take some time before the packages are available in Maven Central.

https://github.com/NitorCreations/nflow/releases/tag/5.6.0

**Comment by efonsell** [comment]
5.5.1 was never released but 5.6.0 is not available.
