### ISSUE TITLE
Can not create Kotlin workflows

### ISSUE THREAD

**Issue by dahedgehog** [NitorCreations/nflow#311]
It's not possible to create pure Kotlin workflows extending WorkflowDefinition because WorkflowState must be and enum. This creates a clash between name property in Kotlin enum and name() method in WorkflowState interface. Example of non-functioning code:

```
enum class State(private val _type: WorkflowStateType, private val _desc: String) : WorkflowState {
    repeat(WorkflowStateType.start, "Start state"),
    error(WorkflowStateType.manual, "Error state");

    override fun getDescription() = _desc
    override fun getType() = _type
}
```

**Comment by jsyrjala** [comment]
nFlow 5.6.0 was released with this feature.

https://github.com/NitorCreations/nflow/releases/tag/5.6.0
