### ISSUE TITLE
Not possible to use database create scripts as-is

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/nflow#318]
Currently it is not possible to execute most of the database create scripts to empty database, because they contain commands that assume that some objects already exists.

For example
https://github.com/NitorCreations/nflow/blob/master/nflow-engine/src/main/resources/scripts/db/postgresql.create.ddl.sql#L39
contains this:
```
drop index nflow_workflow_activation;
create index nflow_workflow_activation on nflow_workflow(next_activation, modified);
```

The drop will fail if that index does not already exists.

The tests are executing these scripts but they explicitly ignore failed drop statements.
https://github.com/NitorCreations/nflow/blob/master/nflow-engine/src/test/java/io/nflow/engine/internal/dao/BaseDaoTest.java#L45

These scripts should be runnable as-is so that the end user doesn't have to modify them.

**Comment by jsyrjala** [comment]
#322 fixes this issue for PostgreSQL.

**Comment by efonsell** [comment]
Fixed in https://github.com/NitorCreations/nflow/releases/tag/5.7.0

**Comment by efonsell** [comment]
#347 fixes this issue for H2 and MSSQL.

**Comment by efonsell** [comment]
6.0.0 contains more index improvements, is there still something that does not work?

**Comment by efonsell** [comment]
Closing, reopen of open new issue if you hit into problems with some database.
