### ISSUE TITLE
Error when configuring external database (H2)

### ISSUE THREAD

**Issue by wendersonferreira** [NitorCreations/nflow#408]
Hello, how are you? I have a problem configuring application.properties to point to an external h2 database, I get this exception Class ""io.nflow.engine.internal.storage.db.H2ModifiedColumnTrigger". My application use h2 as primary database, i'm using version (7.2.0)

**Comment by efonsell** [comment]
Hello,
Can you provide the full stack trace, please?

**Comment by wendersonferreira** [comment]
Thank for you fast answer.I will send it by attachment
[h2-exception.log](https://github.com/NitorCreations/nflow/files/5290954/h2-exception.log)

**Comment by efonsell** [comment]
Are you using external server for H2 database?

"The trigger class must be available in the classpath of the database engine (when using the server mode, it must be in the classpath of the server)."

Ref: http://h2database.com/html/features.html#triggers, https://stackoverflow.com/questions/14124099/cannot-call-trigger-in-h2-db

**Comment by wendersonferreira** [comment]
Thank you, i will try it.

**Comment by wendersonferreira** [comment]
I would like to thank you, it worked in the database classpath. However when executing the application, it possibly tries to recreate applying the script in the db, even a totally new db I get Failed to create the database, possibly already created: Failed to execute SQL script statement.

see in attachment.
[h2-exception-2.log](https://github.com/NitorCreations/nflow/files/5297772/h2-exception-2.log)

**Comment by efonsell** [comment]
These are just warnings, you can either ignore them or you can disable automatic db creation by setting nflow.db.create_on_startup=false (https://github.com/NitorCreations/nflow/wiki/Configuration#nflow-properties-nflow-engine).

**Comment by efonsell** [comment]
You may also want to set nflow.autoinit=false and nflow.autostart=false in the DB server.

**Comment by wendersonferreira** [comment]
OK, thank you a lot, i will check it. Have a nice day
