### ISSUE TITLE
"Save as PNG" produces empty transparent PNG image

### ISSUE THREAD

**Issue by Jalle19** [NitorCreations/nflow#410]
Below this paragraph is an example (you won't be able to see it):

![liigaClipIngest(1)](https://user-images.githubusercontent.com/1106133/96447032-34d8b880-121a-11eb-9caa-28d33732edbe.png)

The image is above this paragraph.

**Comment by efonsell** [comment]
The button will be removed in 7.2.2. PR to restore the functionality would be appreciated.
