### ISSUE TITLE
nFlow explorer does not  fully support HTTPS

### ISSUE THREAD

**Issue by steowens** [NitorCreations/nflow#467]
When nFlow explorer is exposed via HTTPS, the browser issues console errors as follows:

[Warning] [blocked] The page at https://localhost:8888/explorer/index.html was not allowed to display insecure content from http://fonts.gstatic.com/s/opensans/v10/cJZKeOuBrn4kERxqtaUH3ZBw1xU1rKptJj_0jans920.woff2.

[Warning] [blocked] The page at https://localhost:8888/explorer/index.html#!/workflow-definition/sendMessageWorkflow was not allowed to display insecure content from http://fonts.gstatic.com/s/opensans/v10/u-WUoqrET9fUeobQW7jkRZBw1xU1rKptJj_0jans920.woff2.
vendor.863efce5.js:1:1243323

This is not blocking but apparently you have schemes hard coded to http on some of your resources.  Might be better to have these resources default to HTTPS.

**Comment by jsyrjala** [comment]
This got fixed in https://github.com/NitorCreations/nflow/pull/468
