### ISSUE TITLE
Nflow explorer has javascript errors

### ISSUE THREAD

**Issue by steowens** [NitorCreations/nflow#470]
When starting the nflow service in something other than local host the javascript keeps failing with get errors:

Possibly unhandled rejection: {"data":{"timestamp":"2022-01-05T21:38:13.451+00:00","status":404,"error":"Not Found","path":"/explorer/undefined/v1/workflow-executor"},"status":404,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","withCredentials":false,"url":"undefined/v1/workflow-executor","headers":{"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"d385c9e7-3c09-469a-b55f-b12dd12af0b2"}},"statusText":"","xhrStatus":"complete","resource":[]}

The undefined seems to indicate a failed expectation but the javascript is impossible to debug on the explorer:[](url)
![Screen Shot 2022-01-05 at 1 41 22 PM](https://user-images.githubusercontent.com/978310/148293660-2b68800c-2a5a-40fb-ba19-31f910776d22.png)

**Comment by steowens** [comment]
Here is the /explorer/config.js

var Config = function () {
  this.nflowEndpoints  = [
	  {
	    id: 'Garage',
	    title: 'nFlow instance',
	    apiUrl: 'https://garage.iam-test.disney.com/nflow/api',
	    docUrl: 'https://garage.iam-test.disney.com/nflow/ui/doc/'
	  }
	]
  this.radiator = {
    // poll period in seconds
    pollPeriod: 15,
    // max number of items to keep in memory
    maxHistorySize: 10000
  };
};

**Comment by steowens** [comment]
https://garage.iam-test.disney.com/nflow/api/v1/workflow-executor returns a 200 but the UI is mangling the urls somehow.

**Comment by efonsell** [comment]
Hi,
I think you need to have these (default endpoint) settings in your config.js:
```
var Config = function() {
  this.nflowUrl = 'https://garage.iam-test.disney.com/nflow/api';
  this.nflowApiDocs = 'https://garage.iam-test.disney.com/nflow/ui/doc/';
  this.withCredentials = false;

  this.nflowEndpoints = [
    {
      id: 'Garage',
      ....
```

**Comment by efonsell** [comment]
And if you have only one endpoint, you don't need to set `this.nflowEndpoints` at all.

**Comment by steowens** [comment]
@efonsell So that does not seem to be the problem see new screen shots attached.
![Screen Shot 2022-01-07 at 10 16 12 AM](https://user-images.githubusercontent.com/978310/148588717-bb5b9149-ad1d-4d1c-99fd-be6b8e85bb1f.png)
![Screen Shot 2022-01-07 at 10 16 02 AM](https://user-images.githubusercontent.com/978310/148588721-b14cd0a1-a3f0-4492-89c2-bb6c9e243302.png)

**Comment by steowens** [comment]
So I did notice something the undefined is gone but now the URLS are duplicating the host: https://garage.iam-test.disney.com/garage.iam-test.disney.com/nflow/api/v1/workflow-executor

The URL should be https://garage.iam-test.disney.com/nflow/api/v1/workflow-executor

**Comment by efonsell** [comment]
Seems like you are missing one / after https: in nflowUrl. This probably breaks the URL formatting?

**Comment by steowens** [comment]
Actually changing nFlowUrl to = /nflow/api fixed the issue.  Using the fully specified URL was causing the host to be doubled up in the first path parameter.

**Comment by steowens** [comment]
Oh and Duh forgot the '/'
