### ISSUE TITLE
Re-initialize nflow database for testing

### ISSUE THREAD

**Issue by steowens** [NitorCreations/nflow#481]
Hi, we were doing testing with NFLOW and we wanted to purge all existing NFLOW data from Postgres.  But after deleting all tables, triggers and functions, leaving just an empty database, NFLOW failed to start because it would seem that it didn't realize that the tables are gone and it needs to re-create them.  How can we get Nflow working again on deletion of back end workflow data?

We are seeing the following entries in our logs:

17:42:25.518 INFO [main] io.nflow.engine.internal.storage.db.DatabaseInitializer [DatabaseInitializer.java : 40] - Creating database populator using script 'scripts/db/postgresql.create.ddl.sql'
17:42:25.596 WARN [main] io.nflow.engine.internal.storage.db.DatabaseInitializer [DatabaseInitializer.java : 31] - Failed to create the database, possibly already created: Failed to execute SQL script statement #1 of class path resource [scripts/db/postgresql.create.ddl.sql]: create type workflow_status as enum ('created', 'executing', 'inProgress', 'finished', 'manual'); nested exception is org.postgresql.util.PSQLException: ERROR: type "workflow_status" already exists

**Comment by jsyrjala** [comment]
When you are dropping other objects, try dropping also types.
```
DROP TYPE IF EXISTS workflow_status;
```

**Comment by steowens** [comment]
Thank you!   It would be awesome if that statement were added to the scripts/db/postgresql.create.ddl.sql.
