### ISSUE TITLE
Retryable workflows don't seem to execute when recovered

### ISSUE THREAD

**Issue by steowens** [NitorCreations/nflow#482]
I am not sure I am interpreting this correctly but I have a timer workflow which retries every 30 minutes.  But it doesn't seem to work when the nflow service is restarted or a new container set is deployed.  What exactly is the recovered state?
![Screen Shot 2022-01-24 at 12 26 41 PM](https://user-images.githubusercontent.com/978310/150859598-e1bae610-b405-4546-8b66-5637827830cf.png)

**Comment by steowens** [comment]
Another example is this.  In this case the newRequest should transition to awaitApproval which is a manual state.  But when the system recovers the workflow this transition doesn't seem to happen.
![Screen Shot 2022-01-24 at 1 11 13 PM](https://user-images.githubusercontent.com/978310/150865594-bcff2752-022e-4c81-9176-7b453469ff94.png)

**Comment by efonsell** [comment]
Can you see any currently active executors in the Executors view? If yes, find the executor_id value of the workflow instance that seems to be stuck (from the database, it is not visible in the UI) and check if it matches any active executor.

When you shut down your containers, do you shut nFlow down gracefully?

**Comment by steowens** [comment]
I probably am not shutting down nFlow gracefully.  Were running in Fargate.  Fargate manages the starting and stopping of containers.  It does go through a draining process.  Is there anything explicit I need to do to shut down gracefully?

**Comment by steowens** [comment]
This is what I am seeing in the nflow_executor table:
![Screen Shot 2022-01-24 at 1 44 49 PM](https://user-images.githubusercontent.com/978310/150870098-9f902e05-80d8-48d9-81a2-eff937286c5f.png)

**Comment by steowens** [comment]
My understanding of modern containerized development is that we should assume that containers can arbitrarily be killed.  Does this impact the ability of nFlow to recover and continue?

**Comment by efonsell** [comment]
Thanks, the only active executor seems to be `7`, can you check the executor_id values in the `nflow_workflow` table also?

The nFlow recovery process is designed to handle unexpected terminations of the executor. The benefit of graceful shutdown is that the workflow instances can be processed immediately, instead of waiting for the died executor heartbeat to expire before the instances that were being processed of the died executor can be recovered.

Based on the logging and the stopped timestamps, nFlow has been shut down gracefully, and there should not be any instances to be recovered. Maybe those instances were left by some other executor that has not been shut down gracefully? Anyway, also those should be recovered. But I would need to know the executor_id of the instances to analyze further.

**Comment by efonsell** [comment]
The status `executing` means that some executor is processing the workflow instance, preventing any other executor to process that instance. If the executor identified by the `nflow_workflow.executor_id` has died, the instance should be recovered by some active executor. If the executor is active, you should see some logging in that container, and it should be processing the instance.

**Comment by steowens** [comment]
Here is what were seeing in the nflow_workflow table:
![Screen Shot 2022-01-24 at 2 01 36 PM](https://user-images.githubusercontent.com/978310/150872384-89dc65cc-eff7-46cf-81f8-6fe06d3a560a.png)

**Comment by steowens** [comment]
I also notice that there are errors happening at the PGSQL layer concurrent with duplicate log entries for the same line of code in the same instance.  Right now were only running one single instance. Not sure if the two things are related.

21:20:42.445 INFO [nflow-executor-3] com.disney.cst.iam.garage.service.modules.workflows.AccessRequestWorkflow [AccessRequestWorkflow.java : 258] - Shifting workflowState to awaitApproval:Request awaiting approval
--
21:20:42.445 INFO [nflow-executor-3] com.disney.cst.iam.garage.service.modules.workflows.AccessRequestWorkflow [AccessRequestWorkflow.java : 258] - Shifting workflowState to awaitApproval:Request awaiting approval
21:20:42.907 DEBUG [nflow-executor-2] com.disney.cst.iam.garage.service.modules.workflows.SendMessageWorkflow [SendMessageWorkflow.java : 98] - Processing request deae3e89-2b8c-495e-85d9-02d3443f4665
21:20:42.907 DEBUG [nflow-executor-2] com.disney.cst.iam.garage.service.modules.workflows.SendMessageWorkflow [SendMessageWorkflow.java : 98] - Processing request deae3e89-2b8c-495e-85d9-02d3443f4665
21:20:42.976 WARN [nflow-executor-3] io.nflow.engine.internal.dao.WorkflowInstanceDao [WorkflowInstanceDao.java : 200] - Failed to insert workflow instance
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [with wf as (insert into nflow_workflow(type, priority, parent_workflow_id, parent_action_id, business_key, external_id, executor_group, status, state, state_text, next_activation, workflow_signal) values (?, ?, ?, ?, ?, ?, ?, ?::workflow_status, ?, ?, ?, ?) returning id), ins12 as (insert into nflow_workflow_state(workflow_id, action_id, state_key, state_value) select wf.id,0,?,? from wf), ins14 as (insert into nflow_workflow_state(workflow_id, action_id, state_key, state_value) select wf.id,0,?,? from wf), ins16 as (insert into nflow_workflow_state(workflow_id, action_id, state_key, state_value) select wf.id,0,?,? from wf) select wf.id from wf]; ERROR: duplicate key value violates unique constraint "nflow_workflow_uniq"
Detail: Key (external_id, type, executor_group)=(c357e346-6e88-44ed-bb11-1acbd5043cde, sendMessageWorkflow, nflow) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "nflow_workflow_uniq"
Detail: Key (external_id, type, executor_group)=(c357e346-6e88-44ed-bb11-1acbd5043cde, sendMessageWorkflow, nflow) already exists.
at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:757)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:879)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:906)
at io.nflow.engine.internal.dao.WorkflowInstanceDao.insertWorkflowInstanceWithCte(WorkflowInstanceDao.java:198)
at io.nflow.engine.internal.dao.WorkflowInstanceDao.insertWorkflowInstance(WorkflowInstanceDao.java:171)
at io.nflow.engine.internal.dao.WorkflowInstanceDao$2.doInTransactionWithoutResult(WorkflowInstanceDao.java:356)
at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
at io.nflow.engine.internal.dao.WorkflowInstanceDao.updateWorkflowInstanceWithTransaction(WorkflowInstanceDao.java:347)
at io.nflow.engine.internal.dao.WorkflowInstanceDao.updateWorkflowInstanceAfterExecution(WorkflowInstanceDao.java:328)
at io.nflow.engine.internal.dao.WorkflowInstanceDao$FastClassBySpringCGLIB$f1fc6e3.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
at io.nflow.engine.internal.dao.WorkflowInstanceDao$EnhancerBySpringCGLIB$3ae8f7bd.updateWorkflowInstanceAfterExecution(<generated>)
at io.nflow.engine.internal.executor.WorkflowStateProcessor.persistWorkflowInstanceState(WorkflowStateProcessor.java:332)
at io.nflow.engine.internal.executor.WorkflowStateProcessor.saveWorkflowInstanceState(WorkflowStateProcessor.java:300)
at io.nflow.engine.internal.executor.WorkflowStateProcessor.runImpl(WorkflowStateProcessor.java:201)
at io.nflow.engine.internal.executor.WorkflowStateProcessor.run(WorkflowStateProcessor.java:129)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "nflow_workflow_uniq"
Detail: Key (external_id, type, executor_group)=(c357e346-6e88-44ed-bb11-1acbd5043cde, sendMessageWorkflow, nflow) already exists.
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
... 23 common frames omitted

**Comment by steowens** [comment]
For reference the AccessRequest workflow implements a private method called sendMessage implemented as follows:
`
private void sendMessage(NotificationType notificationType, String requestId, StateExecution execution) {
		try {
			WorkflowInstance childInstance = messageSender.sendMessage(notificationType, requestId);
			execution.addChildWorkflows(childInstance);
		} catch(Exception e) {
			logger.error("Unable to send notification message. Primary workflow will continue.", e);
		}
	}
`

Where MessageSender is implemented as follows:

@Service
public class MessageSender {
	@Autowired
	private WorkflowInstanceService workflowInstances;

	@Autowired
	private WorkflowInstanceFactory workflowInstanceFactory;
	
	public WorkflowInstance sendMessage(NotificationType notificationType, String requestId) {
		String messageId = UUID.randomUUID().toString();
		QueryWorkflowInstances query = new QueryWorkflowInstances.Builder()
				.setExternalId(messageId)
				.build();
		Collection<WorkflowInstance> duplicates = workflowInstances.listWorkflowInstances(query);
		while(!duplicates.isEmpty()) {
			messageId = UUID.randomUUID().toString();
			duplicates = workflowInstances.listWorkflowInstances(query);
		}
		WorkflowInstance childInstance = workflowInstanceFactory
				.newWorkflowInstanceBuilder()
				.setType(SendMessageWorkflow.TYPE)
				.setExternalId(messageId)
				.putStateVariable(SendMessageWorkflow.REQUEST_ID, requestId)
				.putStateVariable(SendMessageWorkflow.MESSAGE_ID, messageId)
				.putStateVariable(SendMessageWorkflow.NOTIFICATION_TYPE, notificationType.name())
				.build();
		workflowInstances.insertWorkflowInstance(childInstance);
		return childInstance;
	}
}

**Comment by jsyrjala** [comment]
> I probably am not shutting down nFlow gracefully. Were running in Fargate. Fargate manages the starting and stopping of containers. It does go through a draining process. Is there anything explicit I need to do to shut down gracefully?

ECS Fargate sends SIGTERM to the process some time before it kills the process (by default 30 seconds before). You can catch the SIGTERM and initiate nFlow graceful shutdown.

https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/

**Comment by efonsell** [comment]
It looks like timerWorkflow (1) has `inProgress` status now, which looks normal. Can you check it again in Explorer?

The error in the logs suggests that accessRequestWorkflow (2) is retrying the newRequest state since it is trying to create a child workflow instance which throws an exception because an instance with same external_id+type already exists. You should probably check before creating the new child instance if it already exists, and add it only if it doesn't.

**Comment by steowens** [comment]
So I put the code above on how we create the child instance.  We generate a guid for the workflow instance ID and just on the off chance that somehow we ended up with a duplicate guid, were checking to see if there are any other workflow instances with the same external ID and we keep trying new guids till the query comes up empty and that is the guid we use see the code in message sender above.  Also were catching all exceptions in the parent workflow sendMessage function and logging them but not regrowing them so the parent workflow should continue on.

Here is the tail end of the implementation of newRequest:

        requestStatus.workflowInstanceId = execution.getWorkflowInstanceId();
	requestStatus.requestDetails.lastUpdate = new Date();
	accessRequestTableRepo.updateEntry(requestStatus);
	if(requestStatus.status == WorkflowState.PENDING_APPROVAL) {
		updateAutoApprovals(requestStatus);
		updateRequestSummaries(requestStatus);
		sendMessage(NotificationType.NEW_ACCESS_REQUEST_PENDING, requestId, execution);
	}
	logger.info("Shifting workflowState to {}:{}", nextAction.getNextState(), nextAction.getReason());
	return nextAction;


Here is the log entry generated before the last line of the function:

22:25:59.805 INFO [nflow-executor-2] com.disney.cst.iam.garage.service.modules.workflows.AccessRequestWorkflow [AccessRequestWorkflow.java : 258] - Shifting workflowState to awaitApproval:Request awaiting approval

We are returning the nextAction to shift to awaitApproval yet in the nFlow explorer the UI shows that the workflow is still in the newRequest state.

When I manually try to bump the workflow to a different state in the explorer I get a 409 error and nothing in the logs to indicate why things went wrong.
![Screen Shot 2022-01-24 at 2 41 11 PM](https://user-images.githubusercontent.com/978310/150877183-cba6d5b1-279f-4fa6-b7cd-e372c0b24228.png)

**Comment by efonsell** [comment]
Oh, you seem to insert the child workflow twice:

1. in `MessageSender.sendMessage`: `workflowInstances.insertWorkflowInstance(childInstance);`
2. in `AccessRequest.sendMessage`: `execution.addChildWorkflows(childInstance);` <- this will cause nFlow to call insertWorkflowInstance after the state is processed, causing the exception

I would remove the first

**Comment by steowens** [comment]
OH! Yes I am.  I am deploying a change to eliminate the addChildWorkflows in AccessRequest.sendMessage.  Do you think this is why I can't get the parent workflow out of newRequest?  I am not throwing any exceptions from the newRequest method and the return line is being called.

**Comment by steowens** [comment]
I just updated my previous comment with the correct image file

**Comment by efonsell** [comment]
`workflowInstances.insertWorkflowInstance(childInstance)` will insert the instance to the database immediately and will throw an exception if a duplicate is found.

`execution.addChildWorkflows(childInstance)` will not insert the instance to the database immediately, so in case there is a duplicate, it will fail in nFlow code that tries to persist the workflow instance state, variables, and the new child workflows after your state method has returned, triggering an automatic retry of the same state. This is the recommended way, since it makes the state processing more atomic - if the new workflow state cannot be updated to the database, the new child workflows will not be inserted to the database either.

**Comment by efonsell** [comment]
409 happens if you try to update the workflow that has status `executing`. You are not allowed to modify such instances with REST or Java API, since it could corrupt the workflow instance state (as it is being processed by nFlow).

**Comment by steowens** [comment]
Interestingly enough when I deployed the fix for the duplicate key violation the system processed the request and moved to awaitingApproval which is a manual state.  If I use the nFlow explorer now to bump it to the checkApproval state which would normally occur each time an approval is submitted, but there are already several approvals, will the system execute the checkApproval step?

**Comment by steowens** [comment]
Thanks for your help. Much appreciated.

**Comment by efonsell** [comment]
You're welcome :)
