### ISSUE TITLE
Nflow postgres spring boot full stack application

### ISSUE THREAD

**Issue by infraorder** [NitorCreations/nflow#501]
Hi there
Currently trying to do an implementation of nflow[7.4.0+] in Springboot
The example fullstack application seems to work however when trying to switch from h2 to postgresql I'm getting the following:

```Consider defining a bean of type 'io.nflow.engine.internal.storage.db.SQLVariants' in your configuration.```

My application.properties looks like this:
```
spring.profiles.active=nflow.db.postgres
logging.level.root=WARN
```

My nflow-engine.properties looks like this:
```
nflow.db.postgresql.driver=org.postgresql.Driver
nflow.db.postgresql.url=jdbc:postgresql://localhost/nflow
nflow.db.postgresql.user=postgres
nflow.db.postgresql.password=*PASS*
```

Is this a known issue or am I missing something?

EDIT: I am using java 11 if that means anything

**Comment by efonsell** [comment]
The profile should be `nflow.db.postgresql`, not `nflow.db.postgres`.

**Comment by efonsell** [comment]
I assume using correct profile fixed the issue, closing this. Please reopen if it didn't help.

**Comment by infraorder** [comment]
Hi @efonsell, yes this was correct.
Many thanks
