### ISSUE TITLE
nflow not registering ui endpoints

### ISSUE THREAD

**Issue by infraorder** [NitorCreations/nflow#543]
Hi there

have been trying to get nflow-explorer-ng working.
have done the following:
- Added this to my pom:
```
<dependency>
    <groupId>io.nflow</groupId>
    <artifactId>nflow-rest-api-spring-web</artifactId>
    <version>8.0.0</version>
</dependency>
```
- Added this to my bootstrap:
```
@Import(RestConfiguration.class)
```
- Added this plugin to my pom:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <executions>
        <execution>
            <id>unpack</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>unpack</goal>
            </goals>
            <configuration>
                <artifactItems>
                    <artifactItem>
                        <groupId>io.nflow</groupId>
                        <artifactId>nflow-explorer-ng</artifactId>
                        <version>8.0.0</version>
                        <type>tar.gz</type>
                        <overWrite>true</overWrite>
                        <outputDirectory>${project.build.directory}/static/explorer</outputDirectory>
                    </artifactItem>
                </artifactItems>
            </configuration>
        </execution>
    </executions>
</plugin>
```
Upon looking at the endpoints that are registered I have the following:
```
{GET [/nflow/api/v1/workflow-instance/id/{id}], produces [application/json]} io.nflow.rest.v1.springweb.WorkflowInstanceResource#fetchWorkflowInstance(long, Set, String, boolean, Long)
{PUT [/nflow/api/v1/workflow-instance/{id}/signal], consumes [application/json], produces [application/json]} io.nflow.rest.v1.springweb.WorkflowInstanceResource#setSignal(long, SetSignalRequest)
{PUT [/nflow/api/v1/workflow-instance/{id}/wakeup], consumes [application/json], produces [application/json]} io.nflow.rest.v1.springweb.WorkflowInstanceResource#wakeup(long, WakeupRequest)
{GET [/nflow/api/v1/workflow-executor], produces [application/json]} io.nflow.rest.v1.springweb.WorkflowExecutorResource#listWorkflowExecutors()
{POST [/user/enroll/auth], consumes [application/json], produces [application/json]} com.devshackintl.vsuite.vgateway.enrollment.api.controller.UserEnrollmentControllerImpl#processAuthUserEnrollment(String, UserEnrollmentRequestDto)
{GET [/nflow/api/v1/statistics], produces [application/json]} io.nflow.rest.v1.springweb.StatisticsResource#queryStatistics()
{GET [/nflow/api/v1/workflow-instance/id/{id}], produces [application/json]} io.nflow.rest.v1.springweb.WorkflowInstanceResource#fetchWorkflowInstance(long, Set, String, boolean, Long)
{GET [/nflow/api/v1/workflow-executor], produces [application/json]} io.nflow.rest.v1.springweb.WorkflowExecutorResource#listWorkflowExecutors()
```

but nothing related to ui seems to be registered.
please let me know what is missing from my configuration.

**Comment by eputtone** [comment]
nFlow Explorer NG is a single page application, so it's static HTML and Javascript served from any web server. It uses the REST endpoints listed in your log snippet, but as as Explorer itself is just static content there is no additional resources for the server to register.

Your `maven-dependency-plugin` configuration extracts the static files under `/static/explorer` directory in the classpath. If you're using Spring Boot, it serves the static files under `/static` directory in web root [by default](https://www.baeldung.com/spring-mvc-static-resources), without logging anything (at least on default log level). Then Explorer NG might already be deployed under `http://localhost:8080/explorer/index.html`

The minimal working example of the above is [here](https://github.com/NitorCreations/nflow/tree/master/nflow-examples/spring-boot/full-stack/maven). You can use it as a reference.

If you are not using Spring Boot, then you need to use some other web server to serve the Explorer static files ([from Maven Central](https://search.maven.org/remotecontent?filepath=io/nflow/nflow-explorer-ng/8.0.0/nflow-explorer-ng-8.0.0.tar.gz)), and replace the default `config.js` by one that tells Explorer where the REST endpoints are deployed.

The working example does use nFlow Explorer NG, though [the wiki instructions](https://github.com/NitorCreations/nflow/wiki/Spring-Boot-guide#full-stack-example) for setting it up are not yet updated from Explorer to Explorer NG. The same principles apply though, the main differences are in `config.js` syntax, artifact name and in the URL where Explorer NG is available.

And thanks for the input, we can use it to improve the instructions. Tell us if the answer is not sufficient to get Explorer NG working.
