### ISSUE TITLE
nflow-explorer-ng issue with calls to API

### ISSUE THREAD

**Issue by RealZimboGuy** [NitorCreations/nflow#562]
when the API is not available the nflow-explorer-ng does not have a delay on retry, as such hundreds of requests are sent. 

please put a small delay timer on the retry

![image](https://user-images.githubusercontent.com/15829080/187250302-41f715b3-8681-4d82-8ec2-eb44e7f10461.png)

**Comment by efonsell** [comment]
Fixed in #563
