### ISSUE TITLE
nflow-exporer-ng date format discussion

### ISSUE THREAD

**Issue by zahariaca** [NitorCreations/nflow#583]
Noticed that the date format in the UI uses 24 for midnight, more commonly 00
This happens in: https://github.com/NitorCreations/nflow/blob/599884ebe32c4534bfae3353739a8f39a5d66617/nflow-explorer-ng/src/utils.ts#L21

E.g:
![image](https://user-images.githubusercontent.com/17591878/212902799-bd033be9-3f46-4ee0-882c-6c35dd45bdfb.png)

Is this intentional? Wouldn't it be more standard if the formatter would use **HH** instead of **kk**?

**Comment by jsyrjala** [comment]
HH would be also ok as a format. PR is welcome!

**Comment by zahariaca** [comment]
made change in: https://github.com/NitorCreations/nflow/pull/585

**Comment by efonsell** [comment]
Fixed in #585
