### ISSUE TITLE
nflow is not compatible with Spring Boot 3

### ISSUE THREAD

**Issue by cvasii** [NitorCreations/nflow#595]
nflow is not compatible with Spring Boot 3, because of the beans adnotated with javax.inject.Named (e.g. io.nflow.engine.internal.dao.MaintenanceDao). javax.inject.Named. is not available after upgrading to Spring Boot 3.

**Comment by cvasii** [comment]
One quick fix could be replacing javax.inject.Named with spring's specific annotations.

**Comment by efonsell** [comment]
Fixed in 9.0.0
