### ISSUE TITLE
explorer display of state variables in alphabetic order

### ISSUE THREAD

**Issue by RealZimboGuy** [NitorCreations/nflow#638]
Hi, 

i would like if possible to have the state variables in explorer displayed in order, any thoughts and opinions ? i could look at doing a PR.

![image](https://github.com/NitorCreations/nflow/assets/15829080/7ce712f5-42e5-4374-8c2e-e3a992e4745c)

so from the java side a brief look it might work by adding an order by here 

![image](https://github.com/NitorCreations/nflow/assets/15829080/80471888-3b31-4456-8699-1c93d9c365be)

or alternatively post process the list of state variables on the frontend side ?

**Comment by efonsell** [comment]
I would prefer doing this in frontend side.

**Comment by RealZimboGuy** [comment]
> I would prefer doing this in frontend side, PR would be great!

done a PR, was actually a nice and small change to just add a sort on the frontend
